### PR TITLE
Populate link “Find an OSH consultant”

### PR DESCRIPTION
**Pull request by reinhardt**
syslabcom/scrum#1164

### CODE REVIEW

**Comment by ale-rt** [comment]
What is content expected to be?
I suppose a `euphorie.page`.

If yes please check https://github.com/euphorie/Euphorie/pull/587. 

It was necessary to me toactually display this page without having a:
```
  Module Products.CMFDynamicViewFTI.browserdefault, line 88, in __call__
RecursionError: maximum recursion depth exceeded in comparison
```

**Review by ale-rt — APPROVED** [review]
Ok.
Is there a reason why you are not using portal catalog to find objects with `getId="consultants"` ?

**Comment by reinhardt** [comment]
I know exactly where the objects are, so there is no need to find them.

Any reason why I should use the portal catalog?

**Comment by ale-rt** [comment]
> I know exactly where the objects are, so there is no need to find them.
> 
> Any reason why I should use the portal catalog?

Because you are iterating over `objectValues` and that can be potentially lots of objects to wake up before you get the proper one. 
In addition, there are security quirks.

That should be just a minor problem in a real world scenario, in fact I approved the PR.

Just consider these remarks for the next time.

**Comment by reinhardt** [comment]
Great, thanks for elaborating.

**Pull request merged**
