### PR TITLE
Add euphorie.htmllaundry module

### PR DESCRIPTION
**Pull request by mauritsvanrees**
The original ``htmllaundry`` package fails with ``lxml`` 5.2 (Plone 6.0.11).

Just thinking: alternatively we could fix `htmllaundry` and push a new version to PyPI.  We do have access: https://pypi.org/project/htmllaundry/

We have already fixed this in at least one other project, and Alessandro and me identified at least one other project that uses it.

### CODE REVIEW

**Comment by mauritsvanrees** [comment]
If someone gives me write access to https://github.com/syslabcom/htmllaundry I can push a change there and create a PR.

**Comment by pilz** [comment]
> If someone gives me write access to https://github.com/syslabcom/htmllaundry I can push a change there and create a PR.

I added you!

**Comment by mauritsvanrees** [comment]
> > If someone gives me write access to https://github.com/syslabcom/htmllaundry I can push a change there and create a PR.
> 
> I added you!

Thanks @pilz.

Alternative PR created: https://github.com/syslabcom/htmllaundry/pull/2

**Review by ale-rt — APPROVED** [review]

**Comment by ale-rt** [comment]
I would very much prefer going with this version rather than going on with the fork.

**Pull request merged**
