### PR TITLE
clean up unused tools_threshold

### PR DESCRIPTION
**Pull request by reinhardt**
I also checked tno and daimler and it's not used there either.

See also #559 
https://github.com/syslabcom/scrum/issues/1137

### CODE REVIEW

**Review by ale-rt — CHANGES_REQUESTED** [review]
Is it me overlooking, or this seems incomplete?
```
ale@avo:~/Code/plone/projects/quoira/oira/src/Euphorie$ rg -l tools_threshold
src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/portlet-available-tools.pt
src/euphorie/client/browser/templates/new-session-test.pt
```

**Comment by ale-rt** [comment]
The threshold was 12 and was removed here:
https://github.com/euphorie/Euphorie/commit/5d46c324fdbbe293c43d75ed69c9cecfa8429078

**Comment by reinhardt** [comment]
To me it looks fine. Are you sure you're on the right branch?

```
reinhardt@joy:/srv/oira/oira.application.buildout/src/Euphorie (cleanup-tools-threshold *)
[16:52:37]$ rg -l tools_threshold
reinhardt@joy:/srv/oira/oira.application.buildout/src/Euphorie (cleanup-tools-threshold *)
[16:52:39]$
```

**Comment by ale-rt** [comment]
I am pretty sure :)
It might be a bug on ripgrep, try with grep:
```
ale@avo:~/Code/plone/projects/daimlertruck/src/Euphorie$ git fetch 
ale@avo:~/Code/plone/projects/daimlertruck/src/Euphorie$ git diff origin/main |cat
ale@avo:~/Code/plone/projects/daimlertruck/src/Euphorie$ rg -l tools_threshold
src/euphorie/client/browser/country.py
src/euphorie/client/browser/templates/new-session-test.pt
src/euphorie/client/browser/templates/portlet-available-tools.pt
ale@avo:~/Code/plone/projects/daimlertruck/src/Euphorie$ grep -R tools_threshold
grep: src/euphorie/client/browser/__pycache__/country.cpython-38.pyc: binary file matches
src/euphorie/client/browser/templates/portlet-available-tools.pt:         threshold view/tools_threshold;
src/euphorie/client/browser/templates/new-session-test.pt:                 threshold view/tools_threshold;
src/euphorie/client/browser/country.py:    tools_threshold = 0
```

**Comment by reinhardt** [comment]
But my branch is this one:

https://github.com/euphorie/Euphorie/blob/cleanup-tools-threshold/src/euphorie/client/browser/templates/portlet-available-tools.pt

Regular grep doesn't find it either:

```
oira@oira:~/oira.application.buildout/src/Euphorie (cleanup-tools-threshold)
[07:25:57]$ grep -R tools_threshold
.git/logs/HEAD:4cd878b97fc5bdd61e323b5e473b150bcc1d13b5 52962c9732b1a31744bb1a18a67a8861e9ea2604 Manuel Reinhardt <reinhardt@syslab.com> 1683629247 +0200       commit: clean up unused tools_threshold
.git/logs/refs/stash:9fd860748ee055913eb08d819d05e1ae8c3e8ad0 c9c9449f7a16bff41569f41b3ae5b67850ced26b Manuel Reinhardt <reinhardt@syslab.com> 1683696357 +0200 WIP on cleanup-tools-threshold: 52962c973 clean up unused tools_threshold
.git/logs/refs/heads/cleanup-tools-threshold:4cd878b97fc5bdd61e323b5e473b150bcc1d13b5 52962c9732b1a31744bb1a18a67a8861e9ea2604 Manuel Reinhardt <reinhardt@syslab.com> 1683629247 +0200 commit: clean up unused tools_threshold
grep: prototype/.bundle/bin/bundle: No such file or directory
grep: prototype/.bundle/bin/bundler: No such file or directory
grep: src/euphorie/client/browser/__pycache__/country.cpython-38.pyc: binary file matches
oira@oira:~/oira.application.buildout/src/Euphorie (cleanup-tools-threshold)
[07:26:01]$
```

Please stop making me doubt my sanity :wink:

**Comment by ale-rt** [comment]
Sorry, my bad

**Review by ale-rt — APPROVED** [review]

**Pull request merged**
