### PR TITLE
Keep the upgrades together so they can run together

### PR DESCRIPTION
**Pull request by ale-rt**
This empties https://github.com/euphorie/Euphorie/tree/main/src/euphorie/upgrade/client/v1 (which might be probably removed) and moves the upgrade steps here: https://github.com/euphorie/Euphorie/tree/main/src/euphorie/upgrade/deployment/v1

### CODE REVIEW

**Review by reinhardt — APPROVED** [review]

**Comment by reinhardt** [comment]
Very good step! We may also want to consolidate https://github.com/euphorie/Euphorie/tree/main/src/euphorie/deployment/upgrade

**Comment by reinhardt** [comment]
I'm getting an error that prevents starting the instance on daimler-oira-test:

```
Traceback (most recent call last):
  File "/home/daimler/daimler.buildout/eggs/zope.configuration-4.4.0-py3.8.egg/zope/configuration/config.py", line 792, in execute_actions
    callable(*args, **kw)
  File "/home/daimler/daimler.buildout/eggs/ftw.upgrade-3.0.3-py3.8.egg/ftw/upgrade/directory/zcml.py", line 74, in upgrade_step_directory_action
    for upgrade_info in scanner.scan():
  File "/home/daimler/daimler.buildout/eggs/ftw.upgrade-3.0.3-py3.8.egg/ftw/upgrade/directory/scanner.py", line 27, in scan
    self._load_upgrades_directory()
  File "/home/daimler/daimler.buildout/eggs/ftw.upgrade-3.0.3-py3.8.egg/ftw/upgrade/directory/scanner.py", line 107, in _load_upgrades_directory
    imp.load_module(self.dottedname, fp, str(pathname), description)
  File "/usr/lib/python3.8/imp.py", line 244, in load_module
    return load_package(name, filename)
  File "/usr/lib/python3.8/imp.py", line 216, in load_package
    return _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 844, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1129, in get_code
  File "<frozen importlib._bootstrap_external>", line 573, in _classify_pyc
ImportError: bad magic number in 'euphorie.upgrade.client.v1': b'\x03\xf3\r\n'
```

**Comment by ale-rt** [comment]
Clear the __pycache__ folders

**Comment by reinhardt** [comment]
Thanks for the hint; deleting `*.pyc` did the trick!

**Pull request merged**
