### PR TITLE
Rich text (tiptap) for measures action

### PR DESCRIPTION
**Pull request by reinhardt**
Hide whitespace changes when checking the diff.

Refs syslabcom/scrum#444

### CODE REVIEW

**Review by ale-rt — COMMENTED** [review]
Please check my comment.

Did you investigate the possible security implications of this change?

**Comment by reinhardt** [comment]
> Did you investigate the possible security implications of this change?

No, thanks for pointing it out.

The only vector I can imagine is to add some malicious content like a javascript to the markup. That is currently stripped out before it is used in the training, but it should probably be stripped out on saving already. I noticed that the comment field (“Notes”) has the same issue.

**Comment by reinhardt** [comment]
> That is currently stripped out before it is used in the training, but it should probably be stripped out on saving already.

This is now addressed in my latest commit.

> I noticed that the comment field (“Notes”) has the same issue.

I'll fix this in another PR.

**Comment by reinhardt** [comment]
@ale-rt, do you have time to give this another quick look?

**Review by ale-rt — APPROVED** [review]

**Comment by reinhardt** [comment]
:heart:

**Pull request merged**
